### ISSUE TITLE
Probably wrong typing in fromEvent

### ISSUE THREAD

**Issue by Nedgeva** [zpnester/bs-rxjs#1]
Hello!
First of all, thank you for great job you did while porting typings to ReasonML/BS.

I found that `fromEvent` probably has wrong typings for target argument.]
Now it's `Dom.eventTarget` but probably it's should be `Dom.element`.

**Comment by zpnester** [comment]
[fromEvent.ts](https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/fromEvent.ts#L50) 
fromEvent has somewhat complicated input parameter in TypeScript 
but generally it accepts [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget)

You need to convert Element to EventTarget with
```reason
external asEventTarget: Dom.element => Dom.eventTarget = "%identity";
```

`bs-webapi` has such conversion
[Webapi__Dom__EventTarget.re](https://github.com/reasonml-community/bs-webapi-incubator/blob/master/src/Webapi/Webapi__Dom/Webapi__Dom__EventTarget.re#L2)

**Comment by Nedgeva** [comment]
Great, thanks! Pesronally i don't like type castings, but seems like it's the only way.
